name: sem1
version: 0.0.0

ghc-options: -Wall

dependencies:
 - base == 4.*

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - sem1
      - hspec == 2.*
