name: sem2
version: 0.0.0

ghc-options: -Wall

dependencies:
 - 'base >= 4.7 && < 5'

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - sem2
      - hspec == 2.*
